""""This module is kind of used as a config file, may be replaced by a configuration file in the future"""


OLD_TERMS_COLLECTION = "terms"
OLD_RELATIONSHIPS_COLLECTION = "relationships"

RELATIONS_COLLECTION = "relations"
RELATIONS_LOCK_COLLECTION = "relations_lock"

TERMS_COLLECTION = "terms"

USLS_COLLECTION = "usls"
TEMPLATES_COLLECTION = "templates"

RELATION_COMPUTING = 'RELATION COLLECTION RECOMPUTING'
DROP_RELATIONS = 'DROPPING RELATIONS COLLECTION'
SCRIPT_INSERTION = 'INSERTING SCRIPT'
SCRIPT_DELETION = 'DELETING SCRIPT'
TAG_LANGUAGES = ["FR", "EN"]

DB_NAME_USERS = ""

USERS_COLLECTIONS = ""

# Script specific
ROOT_PARADIGM_TYPE = 'ROOT_PARADIGM'
SINGULAR_SEQUENCE_TYPE = 'SINGULAR_SEQUENCE'
PARADIGM_TYPE = 'PARADIGM'

