from .propositions import GraphCheckerHandler, WordGraphCheckerHandler, GraphSavingHandler, WordGraphSavingHandler
from handlers.commons import SearchTermsHandler, ElementDecompositionHandler
from .usl import TextDecompositionHandler, TextValidatorHandler, HyperTextValidatorHandler

